name: Docker Image CI

on: 
  schedule:
    - cron: '0 10 * * 0'
  push:
    branches:
      - 'master'
jobs:
  build-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Watchtower ECR Helper Docker Image
        uses: docker/build-push-action@v2
        with:
          tags: buckhamduffy/watchtower-ecr-helper:latest
          push: true
          context: ./watchtower-ecr-helper/

  build-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Base Docker Image
        uses: docker/build-push-action@v2
        with:
          target: base
          push: true
          context: ./nginx-php/
          tags: |
            buckhamduffy/php-nginx-php:latest
            buckhamduffy/php-nginx-php:php7.4
          

      - name: Build and Push MSSQL Docker Image
        uses: docker/build-push-action@v2
        with:
          target: mssql
          push: true
          context: ./nginx-php/
          tags: |
            buckhamduffy/php-nginx-php:mssql
            buckhamduffy/php-nginx-php:php7.4-mssql